apiVersion: apps/v5
kind: Deployment
metadata:
  name: argocddeploymnt
spec:
  selector:
    matchLabels:
      app: argocdone
  replicas: 5
  template:
    metadata:
      labels:
        app: argocdone
    spec:
      containers:
        - name: argocdcon
          image: narendrapujanaboyina/k8s:5
          ports:
          - containerPort: 5000
